"""
Harmony Search (HS) for Fm | prmu | Cmax.

Harmony Search is inspired by musical improvisation (Geem et al., 2001).
Each "harmony" in the Harmony Memory (HM) is a permutation. New harmonies
are generated by three mechanisms:

1. Memory consideration (HMCR): with probability HMCR, each position
   copies a job from a random harmony in HM.
2. Pitch adjustment (PAR): with probability PAR, a copied job is
   perturbed via an insertion or swap move.
3. Random selection: with probability (1-HMCR), a random job is placed.

Since direct position-wise copying doesn't produce valid permutations,
the discrete adaptation uses order-based crossover from a selected
harmony followed by optional perturbation.

Algorithm:
    1. Initialize HM with HMS harmonies (NEH + perturbations + random).
    2. Generate new harmony:
       a. Select a base harmony from HM (fitness-proportional).
       b. With prob HMCR, use order-based inheritance from base.
       c. With prob PAR, apply insert/swap perturbation.
       d. With prob (1-HMCR), generate random permutation.
    3. If new harmony is better than worst in HM, replace it.
    4. Track global best and repeat.

Notation: Fm | prmu | Cmax
Complexity: O(iterations * HMS * n * m) per iteration.

Reference:
    Geem, Z.W., Kim, J.H. & Loganathan, G.V. (2001). A new heuristic
    optimization algorithm: harmony search. Simulation, 76(2), 60-68.
    https://doi.org/10.1177/003754970107600201

    Gao, K.Z., Pan, Q.K. & Li, J.Q. (2011). Discrete harmony search
    algorithm for the no-idle permutation flowshop scheduling problem
    with the total tardiness criterion. International Journal of
    Advanced Manufacturing Technology, 56, 497-511.
    https://doi.org/10.1007/s00170-011-3197-6
"""

from __future__ import annotations

import sys
import os
import time

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from instance import FlowShopInstance, FlowShopSolution, compute_makespan
from heuristics.neh import neh


def _insert_move(perm: list[int], rng: np.random.Generator) -> list[int]:
    """Apply a random insertion move."""
    n = len(perm)
    if n < 2:
        return list(perm)
    result = list(perm)
    i = rng.integers(0, n)
    job = result.pop(i)
    j = rng.integers(0, n)
    if j >= i:
        j = max(0, j - 1)
    result.insert(j, job)
    return result


def _swap_move(perm: list[int], rng: np.random.Generator) -> list[int]:
    """Apply a random swap move."""
    n = len(perm)
    if n < 2:
        return list(perm)
    result = list(perm)
    i, j = rng.choice(n, size=2, replace=False)
    result[i], result[j] = result[j], result[i]
    return result


def harmony_search(
    instance: FlowShopInstance,
    harmony_memory_size: int = 20,
    hmcr: float = 0.9,
    par: float = 0.3,
    max_iterations: int = 500,
    time_limit: float | None = None,
    seed: int | None = None,
) -> FlowShopSolution:
    """Solve PFSP using Harmony Search.

    Args:
        instance: Flow shop instance.
        harmony_memory_size: Number of harmonies in memory (HMS).
        hmcr: Harmony Memory Considering Rate (0 to 1).
        par: Pitch Adjusting Rate (0 to 1).
        max_iterations: Maximum iterations.
        time_limit: Time limit in seconds.
        seed: Random seed for reproducibility.

    Returns:
        Best FlowShopSolution found.
    """
    rng = np.random.default_rng(seed)
    n = instance.n
    HMS = harmony_memory_size
    start_time = time.time()

    # ── Initialize harmony memory ────────────────────────────────────────
    neh_sol = neh(instance)
    memory: list[list[int]] = [list(neh_sol.permutation)]
    mem_fitness: list[int] = [neh_sol.makespan]

    for i in range(1, HMS):
        if i < HMS // 3:
            perm = list(neh_sol.permutation)
            for _ in range(rng.integers(1, max(2, n // 3))):
                perm = _insert_move(perm, rng)
        else:
            perm = list(range(n))
            rng.shuffle(perm)
        ms = compute_makespan(instance, perm)
        memory.append(perm)
        mem_fitness.append(ms)

    gbest_idx = int(np.argmin(mem_fitness))
    gbest_perm = list(memory[gbest_idx])
    gbest_ms = mem_fitness[gbest_idx]

    for iteration in range(max_iterations):
        if time_limit is not None and time.time() - start_time >= time_limit:
            break

        # ── Generate new harmony ─────────────────────────────────────────
        if rng.random() < hmcr:
            # Memory consideration: select a base harmony
            # Fitness-proportional selection (inverse makespan)
            max_ms = max(mem_fitness)
            fit_vals = [max_ms - f + 1.0 for f in mem_fitness]
            total = sum(fit_vals)
            probs = [v / total for v in fit_vals]
            selected = rng.choice(HMS, p=probs)
            new_perm = list(memory[selected])

            # Pitch adjustment
            if rng.random() < par:
                if rng.random() < 0.5:
                    new_perm = _insert_move(new_perm, rng)
                else:
                    new_perm = _swap_move(new_perm, rng)
        else:
            # Random harmony
            new_perm = list(range(n))
            rng.shuffle(new_perm)

        new_ms = compute_makespan(instance, new_perm)

        # ── Update harmony memory ────────────────────────────────────────
        worst_idx = int(np.argmax(mem_fitness))
        if new_ms < mem_fitness[worst_idx]:
            memory[worst_idx] = new_perm
            mem_fitness[worst_idx] = new_ms

            if new_ms < gbest_ms:
                gbest_ms = new_ms
                gbest_perm = list(new_perm)

    return FlowShopSolution(
        permutation=gbest_perm,
        makespan=gbest_ms,
    )


if __name__ == "__main__":
    instance = FlowShopInstance.random(n=20, m=5, seed=42)

    neh_sol = neh(instance)
    print(f"NEH: makespan = {neh_sol.makespan}")

    hs_sol = harmony_search(instance, max_iterations=500, seed=42)
    print(f"HS:  makespan = {hs_sol.makespan}")
    print(
        f"Improvement: "
        f"{(neh_sol.makespan - hs_sol.makespan) / neh_sol.makespan * 100:.1f}%"
    )
